name: example_CI

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted
    environment: Test Pipeline CI/CD

    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Créer fichier .env
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env 
          echo "DB_NAME=labo02_db" >> .env
          echo "DB_USER=labo02" >> .env 
          echo "DB_PASS=lab02" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env 
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Lancer les tests
        working-directory: src
        run: |
          python3 -m pytest
    
  deploy:
    runs-on: self-hosted
    needs: test   
    steps:
      - name: Checkout dépôt
        uses: actions/checkout@v4

      - name: Déploiement local
        run: |
          cd $GITHUB_WORKSPACE
          echo "Déploiement sur la VM en cours..."

          docker compose down || true
          docker compose up -d --build
